"""empty message

Revision ID: 74f70fa6d2c1
Revises: aa68471ff77d
Create Date: 2025-04-11 12:39:56.059965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f70fa6d2c1'
down_revision = 'aa68471ff77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('teste')

    # ### end Alembic commands ###
