"""empty message

Revision ID: dbd5a23f0f19
Revises: 74f70fa6d2c1
Create Date: 2025-04-11 12:40:14.087164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd5a23f0f19'
down_revision = '74f70fa6d2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('teste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
